apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-api-role
  namespace: argo
rules:
  - apiGroups:
      - ""
    resources:
      - workflows.argoproj.io
      - workfloweventbindings
      - workflowtemplates
      - pods
    verbs:
      - create
      - get
      - list
      - patch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-api-sa
  namespace: argo
    
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-api-role-binding
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-api-role
subjects:
  - kind: ServiceAccount
    name: workflow-api-sa
    namespace: argo
