apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-api
  namespace: argo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: workflow-api
  template:
    metadata:
      labels:
        app: workflow-api
    spec:
      containers:
        - image: suuargo/workflow-api:0.0.2
          name: workflow-api
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: workflow-api-configmap